name: flutterw
repository: https://github.com/hyiso/flutterw

command:
  bootstrap:
    hooks:
      post: dart pub get && dart run husky install
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    includeCommitId: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    hooks:
      preCommit: dart scripts/generate_version.dart && git add packages/flutterw/lib/src/version.g.dart

packages:
  - examples/*
  - packages/*

scripts:

  analyze:
    run: dart analyze . --fatal-infos
    exec:
      concurrency: 1
    description: Run `dart analyze` for all packages.

  test:
    run: dart test --reporter expanded
    exec:
      concurrency: 1
    description: Run `dart test` for specific packages in this project.
    packageFilters:
      flutter: false
      dirExists: test
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  format: dart format -o write .

  format-check:
    exec: dart format . --output=none --set-exit-if-changed
    description: Run `dart format` checks for all packages.