name: "flutterw_monorepo"
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.22.0
  flutterw:
    path: ./packages/flutterw

# This allows us to use flutterw on itself during development.
executables:
  flutterw: flutterw_local