name: flutterw_monorepo
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  flutterw:
    path: packages/flutterw
  commitlint_cli: ^0.4.0-pre.0
  husky: ^0.1.6
  melos: ^3.0.0
  path: ^1.8.0
  yaml: ^3.1.0
  lint_staged: ^0.2.0

# This allows us to use flutterw on itself during development.
executables:
  flutterw: flutterw_local

lint_staged:
  '**.dart': dart fix --apply && dart format --fix