name: flutterw
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  colorize: ^3.0.0
  http: ^0.13.3
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  flutterw: