name: flutterw_hook
description:
  This is a hook package for flutterw]
  You can usage this package to manage flutterw's package hooks.
version: 0.1.0
homepage: https://github.com/hyiso/flutterw
repository: https://github.com/hyiso/flutterw/tree/main/packages/flutterw_clean

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  flutterw: ^0.5.3
  path: ^1.8.0
  yaml_edit: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
