name: flutterw_hook
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  flutterw: ^0.5.1
  path: ^1.8.0
  yaml_edit: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
