name: flutterw
description:
  Flutterw wraps flutter tool to support hooks system.
  Hooks can be both scripts and dart package.
  Adding global or project hook by using flutterw hook command.
version: 0.5.2
homepage: https://github.com/hyiso/flutterw
repository: https://github.com/hyiso/flutterw/tree/main/packages/flutterw

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.1
  yaml: ^3.1.0
  cli_util: ^0.3.5
  cli_wrapper: ^0.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  flutterw: