name: flutterw
description: flutterw wraps flutter tool to support hooks system.
version: 0.5.0-pre.2
homepage: https://github.com/hyiso/flutterw

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.1
  yaml: ^3.1.0
  yaml_edit: ^2.0.3
  cli_util: ^0.3.5
  cli_wrapper: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  flutterw: