name: flutterw
description: flutterw wraps flutter tool with advanced usage.
version: 0.4.0
homepage: https://github.com/hyiso/flutterw

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  colorize: ^3.0.0
  path: ^1.8.1
  yaml: ^3.1.0
  cli_wrapper: 0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  flutterw: