name: flutterw
description:
  Flutterw wraps flutter tool to support scripts and command hooks.
  Hooks are pre, post and command scripts.
version: 0.7.0
homepage: https://hyiso.github.io/flutterw
repository: https://github.com/hyiso/flutterw/tree/main/packages/flutterw

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.1
  yaml: ^3.1.0
  cli_hook: ^0.3.0
  cli_util: ^0.3.5
  cli_wrapper: ^0.5.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  flutterw: