name: cli_wrapper
description: cli_wrapper wraps a cli to support command hooks and plugins system.
version: 0.3.0
homepage: https://github.com/hyiso/flutterw

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
