name: flutterw_clean
description:
  A global hook for flutterw.
  Install this package globally and add it to flutterw hook globally.
  It will work with flutterw clean.
version: 0.1.4
homepage: https://github.com/hyiso/flutterw/tree/main/packages/flutterw_clean

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
