name: flutterw_clean
description: flutterw clean command
version: 0.1.1
homepage: https://github.com/hyiso/flutterw

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
